### ISSUE TITLE
Don't move automatically to quickfix after :GoLint

### ISSUE THREAD

**Issue by adrianlzt** [crispgm/nvim-go#29]
After executing :GoLint (or after saving if it is configured automatically), if there is any error or the linter founds anything, the quickfix window is open and the focus is moved to it.

Could be possible to just open the quickfix but not move to it?

Or maybe move if there is an error, but not with linter errors.

Working on externnal code bases some times return a lot of linter errors and it's annoying to lost the focus in each write.

Thanks!

**Comment by crispgm** [comment]
I think this is a *feature* of vim/nvim, since nvim-go just calls `lopen` for that:
```lua
vim.api.nvim_command(string.format('lopen %d', height))
```

And this will fulfill your request:
```lua
vim.api.nvim_command(string.format('lopen %d | wincmd p', height))
```

This looks good, though I don't know whether it has any side effect of that. I have three plans for this:

1. Change to `lopen %d | wincmd p`
2. Add an option, to control this behaviour
3. Add an `autocmd` and fire the event when popping up the loclist

**Comment by crispgm** [comment]
And this popup actually cause #30

**Comment by crispgm** [comment]
@adrianlzt I think Option #3 is better and you may have a look #31

**Comment by adrianlzt** [comment]
Thanks!! Works perfectly
